### ISSUE TITLE
connexion / reset password

### ISSUE THREAD

**Issue by NouhaylaElfetehi** [chaima-aicheche/Groupe8#12]
*Authentifier les utilisateurs avec leur email et mot de passe.
*reset password par email

![Image](https://github.com/chaima-aicheche/Groupe8/assets/127697772/3e12db01-0f0e-40e3-86f1-3adad0cd8cc0)

![Image](https://github.com/chaima-aicheche/Groupe8/assets/127697772/0ad0bd73-a3a3-47f1-b73f-884f563be136)

**Comment by fabien-ricca** [comment]
Les fonctionnalités de connexions et de reset de mot de passe (avec envoie s'un nouveau mdp par mail) sont fonctionnels.
