### ISSUE TITLE
Récupérer le dernier article lu

### ISSUE THREAD

**Issue by chaima-aicheche** [chaima-aicheche/Groupe8#25]

**Comment by chaima-aicheche** [comment]
Créer une requête SQL pour récupérer le dernier article lu par un candidat. Les informations sur les lectures d'articles sont stockées dans la table Historique_lecture.

Récupérez les informations suivantes sur le dernier article lu :

- ID de l'article
- ID du candidat
- Date de lecture

Triez les enregistrements par date_lecture dans l'ordre décroissant et limitez les résultats à 1.
Retournez les résultats sous forme de tableau JSON.



![Image](https://github.com/user-attachments/assets/61363c59-16bf-42b7-8851-816afe493df6)

**Comment by fabien-ricca** [comment]
Branche : 

backend_ticket_25_Récupérer_le_dernier_article_lu
